### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
# deepspeed: cache/ds_z2_config.json

### dataset
dataset: flowers102_vqa_train_json
# mix_strategy: interleave_over
# interleave_probs: [0.5, 0.5]
template: qwen2_vl
cutoff_len: 16384
# overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
cache_dir: /pasteur/u/lihe50hz/.cache/huggingface/llama-factory

### output
output_dir: working/qwen2_5vl-3b/full-lowlr-sft-flowers102-80000
logging_steps: 10
save_steps: 10
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: qwen2_5vl-3b-full-lowlr-sft-flowers102-80000

### train
per_device_train_batch_size: 1 # using 4 L40s
gradient_accumulation_steps: 4 # using 4 L40s, 4*4
learning_rate: 1.0e-6
# num_train_epochs: 2.0
max_steps: 80000
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
flash_attn: fa2
